/* Problem Statement - 389 - Find the Difference
----------------------------------------------------------------------------------------------------------
You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:
Input: s = "", t = "y"
Output: "y"
----------------------------------------------------------------------------------------------------------
*/

//Method 1 T=O(n) , S=O(1) with 26 ints
char findTheDifference(char* s, char* t) {
    int hash[26] = {0};
    int i=0;
    while(s[i]) {
        hash[s[i] - 'a']++;
        i++;
    }
    i=0;
    while(t[i]) {
        if(hash[t[i]-'a']) {
            hash[t[i]-'a']--;
        }
        else {
            return t[i];
        }
        i++;
    }
    return '\0';
}
//Method 2
char findTheDifference(char* s, char* t) {
    char xor = 0;
    int i=0;
    while(s[i]) {
        xor ^= s[i];
        i++;
    }
    i=0;
    while(t[i]) {
        xor ^= t[i];
        i++;
    }
    return xor;
}
